version: '3'
services:
  image_server:
    container_name: image_server
    image: image_server
    ports:
      - "8001:8999"
    volumes:
      - /tmp:/data/resource/
      - /etc/localtime:/etc/localtime
    restart: always
